[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "date2name"
version = "0.1.0"
description = "A utility script to convert dates to names"
authors = [{name = "Alex S"}]

[project.scripts]
date2name = "date2name:main"